### PR TITLE
ServiceProviders via Models / DB instead of settings

### PR DESCRIPTION
**Pull request by mhindery**
Since everybody asks for this :)

- [x] Make model & admin
- [x] Adapt views & other code to use it
- [x] Adapt tests
- [x] Adapt included example setup
- [ ] Update documentation

### CODE REVIEW

**Comment by askvortsov1** [comment]
Looking good so far, it's a very useful feature! Aside from a few bugfixes (see #60), one part that seems to be a bit wonky is the integration with the old SAML_IDP_SPCONFIG setting. Are these intended to work together, or have the setting as a backup to the models, or as a replacement?

**Comment by askvortsov1** [comment]
A few other ideas for things to include:

1. Specifying a metadata url in addition to the metadata xml field. If filled, this would be tried as the default, and if it fails, the metadata xml could be used as a backup.
2. A metadata xml validator
3. Not requiring restart to load/update new metadata.

I might be able to work on some of these, will try to drop a PR

**Comment by mhindery** [comment]
Thanks for the feedback and the help! As you can see, it's still a work in progress with some wonky bigs, it's functional to the degree where the demo setup works with it, which is a nice one for development, but it's missing some functionality and is rough around the edges in places. Regarding some points you mentioned:

- the metadata part is definitely pretty rough. I had hoped to just be able to use the in-mem string of xml to pass to pysaml, but I didn't find how and after spending a lot of time on it without getting anywhere, I eventually went for the current way of dumping it into a file on the filesystem and inserting that into the metadata of the idp on the fly. Quite ugly, but it works for now, definitely needs more work to investigate that. Also the remote metadata isn't implemented, only a local xml file is possible right now, so that needs to be added as well.
- some added validation and loading functionality is definitely a good addition as well. Feel free to have a go at it if you want to, depending on when I finish other things, I'll look into that otherwise.
- the SAML_IDP_SPCONFIG: I didn't plan on removing that, but to keep it in combination with the service providers config in db. There should always be just a single idp config per 'server' I think, and so creating a model for this doesn't make sense as it is only a single 'global' config. It is a bit cumbersome to update some settings via a redeploy instead of changing them at runtime (in the db), but those are not settings that regularly change (in my case at least). I could define my own class for it, but the current structure aligns with the pysaml documentation and that's nice or recognizability across projects, so my first intention is to keep it like that. Do you have another view on that, or am I making wrong assumptions?

**Comment by askvortsov1** [comment]
That all makes sense. Another question though: I know that a lot of this is integrated into peppelinux's UniAuth, and he's planning on separating out the SAML IDP part into a pip-installable app. That would have a big head start on all these things that we want to implement with djangosaml2idp. Considering overlap in functionality and use cases, are there any plans (or desires) to somehow reconcile UniAuth and djangosaml2idp, or are they permanently splitting off?

**Comment by askvortsov1** [comment]
As a side note, when Service Providers are added during runtime, they don't seem to be registered in the metadata until the server reloads, instead throwing a UnknownSystemEntity issue.

**Comment by askvortsov1** [comment]
> As a side note, when Service Providers are added during runtime, they don't seem to be registered in the metadata until the server reloads, instead throwing a UnknownSystemEntity issue.

Resolved in 31bd6a0, thanks for that!

**Comment by mhindery** [comment]
As this is in pretty ok shape, and there are some other PR's being opened against the state of the code, I'll merge this (but not release to pypi for now). That way other MR's can go against master, and various people contributions don't get lost when merging and squashing.

**Comment by askvortsov1** [comment]
Sounds good (I've been running in production and it works pretty well). I'll reroute my PRs to master then

**Pull request merged**
