### PR TITLE
setup pre-commit config

### PR DESCRIPTION
**Pull request by Amertz08**
This PR sets up pre-commit configuration to enforce some code quality checks

### CODE REVIEW

**Comment by Amertz08** [comment]
As an aside at my work we also setup `black` formatter in our pre-commit hook. This ensures all python files that are changed are properly formatted. I had seen that part of the 1.0 roadmap is some code quality stuff so I thought I'd bring it up. [Here](https://pre-commit.com/hooks.html) is a link to all the supported hooks. I just did some basic ones.

**Comment by mhindery** [comment]
Hi @Amertz08 would it be possible to merge my master branch in your feature branch? The squash and merge into a feature branch and then squash and merge into master doesn't work that well. So preferably the MR's are update with the latest state of master so they can get merged directly.

**Comment by Amertz08** [comment]
@mhindery yeah whatever works for you.

**Comment by Amertz08** [comment]
Don't merge this yet.

**Comment by mhindery** [comment]
Thanks! Regarding the formatter (black or any other), I'm not in favor of that. I prefer the human opinion regarding readability over what they generally make of it. There are some code quality checks in there via pylama, but they leave some room for formatting to allow whatever someone deems readable, only some checks which are unambiguously bad things (e.g. missing whitespace after a comma) are enforced.

**Pull request merged**
