### PR TITLE
Refactoring and Changes Unrelated to User Agreement

### PR DESCRIPTION
**Pull request by askvortsov1**
@mhindery As discussed in https://github.com/OTA-Insight/djangosaml2idp/pull/21#issuecomment-477796034, this is the commits from the previous PR plus some of @peppelinux's commits with the User Agreement Screen, login page, and decorators omitted. I plan to follow up with those in a separate PR after this PR is merged.

### CODE REVIEW

**Comment by peppelinux** [comment]
@askvortsov1 you made an awesome work!
Abount nameID format I made and additional fixture, this is here:
https://github.com/peppelinux/djangosaml2idp/commit/ebcf94943e6731e5f3c1163c0c0cfe2d3fbc82ba#diff-d320bc58b091d46b1ff068902e6a074dR152

About encrypt responses per SP, I fixed this way that permits to have globally an assertion encryption but for single SP the assertions in clear:
https://github.com/peppelinux/djangosaml2idp/commit/de3cd60a60f44f61b5070399d150413ad4a73738#diff-d320bc58b091d46b1ff068902e6a074dR169
(yes, enrypt instead on encrypt!)

Also enhanced NameID opaque with a salt that permit to an username to be unique. I choose to salt the user.pk to have a TransientID that even if a username could be reused it should take another pk!
https://github.com/peppelinux/djangosaml2idp/commit/3309e3285184e1bea2049ddfbf9122d4aef28a5c#diff-957af59c6a0d6db58a741f4e6ffce2dcR34

great

**Comment by peppelinux** [comment]
Hi all,
I made up a fork with many features related to R&S needs in my organization.
Metadata and SP now can be configured via Admin backend. MetadataStore supports local file, local folder, remote endpoint or MDQ servers.

I want to thank you all because everything started from these PR.
If you like the ideas, the features and what I done during these day please put a star.
If you want to contribute I'll appreciate.

Surely I need some refactor to reduce some code repetitions and I'm quite sure that you'll have good suggestions in general. Cheers

**Comment by peppelinux** [comment]
https://github.com/UniversitaDellaCalabria/uniAuth
https://uniauth.readthedocs.io/en/latest/index.html

**Comment by askvortsov1** [comment]
@mhindery Any updates on this?

**Comment by mhindery** [comment]
Yes, I left this way too long, apologies. I'm running through it now, there is a merge conflict because the UserAgreementScreen is still present in there, could you have a look at that? Then I'll merge this today, and can release a new version over the coming days (I'll have a look at it to perhaps clean some things up).

**Pull request closed without merging**
