### PR TITLE
WIP pytest config

### PR DESCRIPTION
**Pull request by Amertz08**
This is very much WIP. Basic changes are as follows.

- Basic Makefile for easier development
- Refactored test util functions into pytest fixtures
- basic pre-commit config for code quality
- integrated usage of `pip-tools` for dev dependencies
    - Should avoid conflicts in underlying dependencies
    - unpinned dependencies
- test alias. `python setup.py test` will run tests
- `xfail` tests for `IdPHandlerViewMixin` that attempt to use `set_sp`

### CODE REVIEW

**Comment by askvortsov1** [comment]
Hey @Amertz08! Thanks a lot for this, testing is definitely one of the aspects where this project is somewhat lacking. At one point I got us up to about 95% coverage, but it's gone somewhat downhill from there unfortunately. One recommendation I'd like to make however: if you're willing to help improve the testing suite, I'd do it against the #51 pull request. A lot of useful features are being added that are changing some of the internal logic, and it's looking like that will be the future of djangosaml2idp. It's generally pretty stable (with my 2 PRs) (I'm running that on production), but severely lacking in testing.

**Comment by Amertz08** [comment]
@askvortsov1 I'll merge that branch into mine and work from there.

**Comment by askvortsov1** [comment]
Awesome, thanks a lot!

**Comment by mhindery** [comment]
Fyi @Amertz08 and @askvortsov1  I've fixed the tests after having merged the aforementioned feature branch and those that are there are all succeeding. If you can update your PR's to go into the master branch again, I'll happily merge them, the pytest / tox additions are definitely useful (and as you mentioned, I should look into having travisCI or something similar getting set up). The current coverage at this point is 73%, which can always go higher :) Especially with the previous release, there were some stupidly obvious bugs in there due to it not being tested, which could have been avoided.

**Comment by askvortsov1** [comment]
Hey @mhindery! You've already merged one of my 2 most recent PRs, the other one, #72 , has been updated. 

As for Travis, I believe the configuration files are already there, so it should be a matter of hooking it up as an open source project. 

And yeah definitely agree on testing. Slowly but surely, djangosaml2idp is approaching a more-or-less mature product (putting SP info in the database + url-based metadata) was a huge change imo, and  our test suite should reflect that.

**Comment by Amertz08** [comment]
@askvortsov1 As far as this PR goes I wouldn't merge it. I basically split most of it off into my other PRs. #71 updates the tox config to run tests for all the necessary python and django versions.

**Comment by Amertz08** [comment]
I'm going to close this given most of the changes have been moved into other PRs.

**Pull request closed without merging**
