### PR TITLE
Refactoring and DRY

### PR DESCRIPTION
**Pull request by askvortsov1**
As of right now, a lot of code is similar between SSOInitView and LoginProcessView, although with differing code styles. This PR separates out these shared components into the IdPHandlerMixin, so that in the future they can be maintained from one place. In summary:

1. I've moved out large chunks of shared/similar code into the IdPHandlerMixin
2. Made it use the overridable login.html template for outgoing responses via the POST binding
3. Minor stylistic changes

### CODE REVIEW

**Comment by askvortsov1** [comment]
@mhindery

**Comment by peppelinux** [comment]
I would like to develop on top of this PR, this is a very usefull refactor. 
@askvortsov1 you made a very good job

**Comment by peppelinux** [comment]
Hi @askvortsov1, as I see the SSOInitView is not used anymore in the code, it don't have any related call. Am I wrong?

**Comment by peppelinux** [comment]
I made a SLO branch on top of this PR and other related to @askvortsov1 fork repository

**Comment by peppelinux** [comment]
Great!

**Comment by mhindery** [comment]
Hi @askvortsov1 , I'm running through the MR now, as I've left this project a bit too long, unfortunately things have piled up a bit. Most of the additions seem great though. One thing I initially do have reservations about is the user agreement screen feature. I don't think this belongs in this package. As saml sso is normally used in corporate systems, the attributes and information being passed between systems is configured by the administrators of each communicating system, and it's not a matter of choice for end-users to allow or deny this. Introducing models is something I ideally want to avoid, as it adds complexity with migrations and other things (e.g. implementing a decent admin).

**Comment by askvortsov1** [comment]
> One thing I initially do have reservations about is the user agreement screen feature. I don't think this belongs in this package. As saml sso is normally used in corporate systems, the attributes and information being passed between systems is configured by the administrators of each communicating system, and it's not a matter of choice for end-users to allow or deny this. Thus I don't see the added value here. Introducing models is something I ideally want to avoid, as it adds complexity with migrations and other things (e.g. implementing a decent admin)

Hi @mhindery! To an extent I agree; according to @peppelinux this feature is useful for EU companies due to the GDPR. While working on implementation I've made sure that this feature is completely optional, highly customizable, and disabled by default, but I do agree that the additional required configuration adds more complexity, not less. I don't think that adding it does too much harm to the project though: maybe it would be good to look through and see if any parts could be trimmed out.

As I understand, most of mine and @peppelinux's changes can be found between this PR, and https://github.com/askvortsov1/djangosaml2idp/pull/7/files. One feature that I'm uncertain about adding is a login form (https://github.com/OTA-Insight/djangosaml2idp/pull/39/commits/71ccfb18aca0cb83627423b1d44607939a89962a). I like that djangosaml2idp is agnostic to the login solution chosen, and I don't see how adding in our own login form presents sufficient benefits to counter the resulting inconveniences.

**Comment by askvortsov1** [comment]
In terms of logistics, there are quite a few commits from @peppelinux in https://github.com/askvortsov1/djangosaml2idp/pull/7 that I think would benefit this project, but likewise a few that I think warrant a bit further discussion. However, considering how many commits are in this PR already, perhaps we can discuss this PR first, and then @peppelinux you could make another PR with what you think should also be included?

**Comment by peppelinux** [comment]
Hi @mhindery I work as a devop in an european academia, in my context SAML2 Is widely used as internal SSO but also in identity federations. Many of these federations was created to let research and scholarship institutions to share their services, to permit their members to be identified without issue credentials. Networks like eduroam, idem, sunet, feide and many others was able to built this kind of paradigm. Internet2 Is part of this standards and many others consortiums in each country share knowledge, tools and experiences to make this possible. The common principles of trust and delegation made this infrastructure very sensibile to personal informations following the imperative to let all this to be transparent, as many as possibile, to the users. Data consent and a consciuos agreement Is a big part of this, in my context where GDPR compliances are the policy and the mandatory model to follow.

The leading software in this scenario Is Shibboleth (internet2). As I am a Django Dev for about 11 years I Need to implement a simple, smart but efficient solution because this kind of software are often implemented on top of monolitics Java servlet and other enterprises stack that personally I discourage use for management and computational costs. 

I used djangosaml2idp as a base and I like It, I want to thank you all to make this possible. If we cannot share a milestone I'll continue my development indipendently, but I'd really like continue sharing security issues and general design improvement related to the core of  pySaml2 implementation and best practices, I found many aspects that could Be improved to open djangosaml2idp to a wider audience

**Comment by mhindery** [comment]
Yeah, I'd prefer to have this MR be split up as some feature are perfectly fine to be merged (I just went to the issues in the repo with some descriptions on them), but the login screen you mention and the agreement screen is something I'd like to review and consider first. Some implementation code-wise I also have some comments on (e.g. the decorator which @peppelinux also mentions) that's merely a practicality, but these discussions are a lot easier when they are in separate MR's. Currently however it's either all changes or nothing, which will block some things unnecessary.

**Comment by askvortsov1** [comment]
I'm somewhat new to open source, so please lmk if there's anything in the following plan that doesn't make sense. I was thinking of taking the following approach:

1. I'll set up a new branch, and use interactive rebase to pick out the commits not related to the user agreement feature. I'll comment out any unit tests / user agreement components in generally unrelated commits
2. I'll go through @peppelinux's branch, and cherry-pick out all commits not related to user-agreement
3. I'll make a new PR for that, and close this one for now.
4. We can make any relevant style changes to this new PR, then merge it
5. We can resume discussion on the user agreement feature, and later on set up a separate PR for any features we decide to integrate into the main project.

Does that sound like an OK plan?

**Comment by peppelinux** [comment]
Great.
I'm following a personal, hard, roadmap and at this Moment I'd have some difficulty to deal too much in wider point of views. One of the best thing of our code Is that Is very Easy to be read, I also think that Will be very Easy to share ideas and then take Just what's needed and nothing else, without waste time to deal with automatico merge and too complex coordination between us. This Is driven by time limite I have, but I would not give up the sharing of our design approaches. It's fun!

**Comment by mhindery** [comment]
Changes are consolidated in https://github.com/OTA-Insight/djangosaml2idp/pull/49, so closing this one.

**Pull request closed without merging**
